name: Quint simulations and tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quint-typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - run: bash scripts/quint-forall.sh typecheck quint/**/*.qnt